### ISSUE TITLE
how to use AdskOAuth Python to implement photoscene 

### ISSUE THREAD

**Issue by rickymf4** [ADN-DevTech/AutodeskOAuthSamples#1]
Dear StephenPreston:
     I'm new to the autodesk recap360 API. I use https://github.com/ADN-DevTech/AutodeskOAuthSamples/blob/master/AdskOAuth%20Python/AdskOAuth.py to do the Authorization and it was successful. However, I add some code:
 
values = {'scenename': "dadatest20160205"}
data = urllib.urlencode (values)
resp, content = client.request ("http://rc-api-adn.autodesk.com/3.1/API/photoscene" + "?" + data, method="POST")
print "photoscene response:"
print resp
print content
 
 after the line 122 "#- Do you other work HERE",  and got failed: 
 
photoscene response:
{'status': '200', 'content-length': '197', 'x-powered-by': 'PHP/5.3.27', 'server': 'Apache/2.2.22 (Amazon)', 'connection': 'keep-alive', 'date': 'Fri, 05 Feb 2016 10:26:49 GMT', 'content-type': 'text/html; charset=UTF-8'}
<?xml version="1.0"?>
<Response>
<Usage>0.024946928024292</Usage>
<Resource>/photoscene</Resource>
<Error>
<code>12</code>
<msg>Bad authentication</msg>
</Error>
</Response>

 I've tried many times all failed. 
Any help would be much appreciated!

**Comment by cyrillef** [comment]
Hi

The Issue is that ReCap API is based on oAuth 1.0a, and you are not using the oAuth 1.0a protocol to pass the data to the API. You might have to consider using the [oAuthLib library](http://oauthlib.readthedocs.org/en/latest/oauth1/client.html) to sign your http request properly (see the example at the end of this page).
Next the ReCap API does not use json input as data, but urlencoded POST / GET. See the documentation [here](http://rc-api-adn.autodesk.com/3.1/api-docs/)

You can find samples for the ReCap API uasge [here](https://github.com/Developer-ReCap-Autodesk) or [here](http://developer-recap-autodesk.github.io/)

cheers
cyrille
